facebook/facebook-swift-sdk

Samples/Catalog/Resources/Base.lproj/Main.storyboard
Samples/Catalog/Sources/LoginManagerViewController.swift
Samples/Catalog/SwiftCatalog.xcodeproj/project.pbxproj
Sources/Login/LoginManager.swift

This is why we need a beta period.
Fixes #3.

Fix failing login with publish permissions when using LoginManager.

---

README.md

Should help avoid problems like #14 in the future.

Clarify versioning instruction for CocoaPods installation.

---

README.md

Should help with issues like #17.

Clarify upgrade instructions for Carthage.

---

README.md

Mention local CocoaPods repo update in README instructions.

---

Samples/Catalog/Sources/AppDelegate.swift
Sources/Core/Common/SDKApplicationDelegate.swift

Add iOS 9.0+ method for opening URLs to ApplicationDelegate.

---

Cartfile.resolved
FacebookCore.podspec
FacebookLogin.podspec
FacebookShare.podspec

Update ObjC SDK dependency to 4.15.

---

Cartfile.resolved
FacebookCore.podspec
FacebookLogin.podspec
FacebookShare.podspec

Update Facebook ObjC SDK dependency to 4.17.

---

FacebookSwift.xcodeproj/project.pbxproj
FacebookSwift.xcodeproj/xcshareddata/xcschemes/FacebookCore.xcscheme
FacebookSwift.xcodeproj/xcshareddata/xcschemes/FacebookLogin.xcscheme
FacebookSwift.xcodeproj/xcshareddata/xcschemes/FacebookShare.xcscheme
Samples/Catalog/SwiftCatalog.xcodeproj/project.pbxproj
Samples/Catalog/SwiftCatalog.xcodeproj/xcshareddata/xcschemes/SwiftCatalog.xcscheme
Sources/Share/ShareError.swift

Minor documentation fixes.

---

Sources/Core/Permissions/Permission.swift

Publicize .name property on Permission.

---

Sources/Core/Permissions/PublishPermission.swift
Sources/Core/Permissions/ReadPermission.swift

Added permissions listed [here](https://developers.facebook.com/docs/facebook-login/permissions).

Expand a set of predefined Read and Publish permissions.

---

Sources/Core/AppEvents/AppEventsLogger.swift

Fix userId setter in AppEventsLogger

---

.github/PULL_REQUEST_TEMPLATE.md
.jazzy.yaml
FacebookCore.podspec
FacebookLogin.podspec
FacebookShare.podspec

Version bump to 0.3.2

---

FacebookCore.podspec
FacebookLogin.podspec
FacebookShare.podspec

This PR adds Swift version into podspecs to improve compatibility with latest CocoaPods and Xcode 10.

Add swift version into podspecs

---

.travis.yml
CHANGELOG.md
Cartfile
Cartfile.resolved

Resolved issues with Carthage for Xcode 10

Resolve Carthage Issues with Xcode 10

---

Cartfile

Moved to semantic versioning for Cartfile, per issue #315

Updated Cartfile to use semantic versioning

---

Cartfile.resolved

Update Cartfile.resolved and git submodule to use 4.39.1 release of the Objective-C SDK.

Update Cartfile.resolved and submodule

---

FacebookCore.podspec
FacebookLogin.podspec
FacebookShare.podspec

Update podspec to use 4.39 (latest version)

Update podspecs for 4.39

---

Cartfile
Cartfile.resolved
FacebookCore.podspec
FacebookLogin.podspec
FacebookShare.podspec

Update Cartfile and podspecs to use 4.40.0 release of `facebook-objc-sdk`

Update Cartfile and podspecs for 4.40

---

README.md
Sources/Share/Content/Photo/Photo.swift

* Adds license to readme
* Fixes link from README to contributing guidelines
* Swiftlint autofixes

Add license to readme

---

.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE/bug_fix.md
.github/PULL_REQUEST_TEMPLATE/feature_addition.md

Added/updated GitHub files for `PULL_REQUEST_TEMPLATE` and `CODEOWNERS`

Added/updated GitHub files for PULL_REQUEST_TEMPLATE and CODEOWNERS

---

Configurations/Shared/Common.xcconfig
Configurations/Shared/Platform/iOS.xcconfig
Configurations/Shared/Platform/macOS.xcconfig
Configurations/Shared/Platform/tvOS.xcconfig
Configurations/Shared/Platform/watchOS.xcconfig
Configurations/Shared/Product/Application.xcconfig
Configurations/Shared/Product/DynamicFramework.xcconfig
Configurations/Shared/Product/LogicTests.xcconfig
Configurations/Shared/Product/StaticFramework.xcconfig
Configurations/Shared/Project/Debug.xcconfig
Configurations/Shared/Project/Release.xcconfig
Configurations/Shared/Warnings.xcconfig

Updated license comments
Test Plan: Visual confirmation is sufficient

Updated license comments for Configuration files

---

CONTRIBUTING.md

Adds reference to Swift.org API Design Guidelines in contributing readme

Encourages use of API Design Guidelines

---

Sources/Core/AccessToken.swift

Makes documentation more resiliant to auto-formatting changes as it is less reliance on white space. See the comments on PR #353 for more information about why this is.
Nothing should be changed but code documentation. Should be easy to manually verify.

Making token documentation more resiliant to formatting changes

---

Sources/Core/GraphRequestQueryItemBuilder.swift
Sources/FacebookCoreTests/GraphRequestQueryItemBuilderTests.swift

Core conversion swiftlint autocorrect

---

FacebookSwift.xcodeproj/project.pbxproj
Sources/Core/ErrorRecoveryStrings.swift
Sources/Core/Localizable.swift
Sources/FacebookCoreTests/ErrorRecoveryStringTests.swift
Sources/FacebookCoreTests/Helpers/LocalizedStringValidation.swift
Sources/FacebookCoreTests/Helpers/SampleLocalizedStrings.swift
Sources/FacebookCoreTests/LocalizableStrings.strings
Sources/FacebookCoreTests/LocalizationsTests.swift
Sources/en.lproj/LocalizableStrings.strings

Enables conversion of string backed enums to their localized variants.
Sets up pattern for testing future localized string enums
All tests should pass.

Localization

---

FacebookSwift.xcodeproj/project.pbxproj
Sources/Core/GraphPath.swift
Sources/Core/GraphRequest.swift
Sources/Core/URLBuilder.swift
Sources/FacebookCoreTests/GraphPathTests.swift
Sources/FacebookCoreTests/GraphRequestMetadataTests.swift
Sources/FacebookCoreTests/GraphRequestTests.swift
Sources/FacebookCoreTests/URLBuilderTests.swift

Gives graph path a stronger type signature
Tests should still pass

Stronger typing for GraphPaths

---

FacebookSwift.xcodeproj/project.pbxproj
Sources/Core/Extensions/Bundle+Extensions.swift
Sources/Core/GraphRequestSerializer.swift
Sources/Core/LoggingBehavior.swift
Sources/Core/Needs Conversion/Logger.swift
Sources/Core/Needs Conversion/Logging.swift
Sources/Core/Needs Conversion/Settings.swift
Sources/FacebookCoreTests/Helpers/FakeBundle.swift
Sources/FacebookCoreTests/Info.plist
Sources/FacebookCoreTests/LoggerTests.swift
Sources/FacebookCoreTests/LoggingBehaviorTests.swift
Sources/FacebookCoreTests/SettingsTests.swift

Settings loads logging behaviors from the main Info.plist and uses those to determine what gets logged for developers using the sdk.
All unit tests should pass.

Logging behavior integration

---

FacebookSwift.xcodeproj/project.pbxproj
FacebookSwift.xcodeproj/xcshareddata/xcschemes/FacebookCore.xcscheme
FacebookSwift.xcodeproj/xcshareddata/xcschemes/FacebookLogin.xcscheme
FacebookSwift.xcodeproj/xcshareddata/xcschemes/FacebookShare.xcscheme
Samples/Catalog/SwiftCatalog.xcodeproj/project.pbxproj
Samples/Catalog/SwiftCatalog.xcodeproj/xcshareddata/xcschemes/SwiftCatalog.xcscheme

Updated to support Xcode 10.2
Test Plan: **Add your test plan here**

Updated to support Xcode 10.2 (latest)

---

Sources/Share/Views/LikableObject.swift

Test Plan: **Add your test plan here**

Resolved Bug in Share Source

---

Sources/Core/AccessTokenWallet.swift
Sources/Core/CoreError.swift
Sources/Core/EmptyDecodable.swift
Sources/Core/Extensions/NotificationName+Extensions.swift
Sources/Core/GraphRequest.swift
Sources/Core/GraphRequestConnection.swift
Sources/Core/GraphRequestSerializer.swift
Sources/Core/Needs Conversion/Settings.swift
Sources/Core/URLSessionTaskProxy.swift
Sources/FacebookCoreTests/AccessTokenTests.swift
Sources/FacebookCoreTests/ErrorConfigurationEntryTests.swift
Sources/FacebookCoreTests/Extensions/RemoteErrorConfigurationEntry+Extensions.swift
Sources/FacebookCoreTests/GraphConnectionProviderTests.swift
Sources/FacebookCoreTests/GraphRequestSerializerTests.swift
Sources/FacebookCoreTests/PermissionTests.swift

Ran `swiftlint autocorrect --format`
Test Plan: Eyes

Core Conversion Format

---

.gitmodules
FacebookCore.podspec
FacebookLogin.podspec
FacebookShare.podspec
README.md

Removed Bolts as a Dep
Test Plan: Build Frameworks

Removed Bolts from Swift SDK

---

Cartfile
Cartfile.resolved

Point to the commit where Swift Support was merged
The branch the Cartfile was pointing to (swift-support) was removed, causing errors on the Carthage checkout.
I modified it to point to the merge commit.
Fixes #421 
Execute Carthage update

Fix Cartfile commit pointer

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.jazzy.yaml
CHANGELOG.md
CONTRIBUTING.md
Cartfile
Cartfile.resolved
FacebookCore.podspec
FacebookLogin.podspec
FacebookShare.podspec
README.md
SUPPORT.md
Samples/Catalog/Sources/AppDelegate.swift
Samples/Catalog/Sources/AppInviteViewController.swift
Samples/Catalog/Sources/CustomAppEventViewController.swift
Samples/Catalog/Sources/GraphAPIPostViewController.swift
Samples/Catalog/Sources/GraphAPIReadViewController.swift
Samples/Catalog/Sources/LoginButtonViewController.swift
Samples/Catalog/Sources/LoginManagerViewController.swift
Samples/Catalog/Sources/ManualAppEventViewController.swift
Samples/Catalog/Sources/ShareAPIViewController.swift
Samples/Catalog/Sources/ShareDialogViewController.swift

Test Plan: **Add your test plan here**

Updated to v0.7.0

---

FacebookSwift.xcodeproj/project.pbxproj
FacebookSwift.xcodeproj/xcshareddata/xcschemes/FacebookCore.xcscheme
Sources/Core/BridgeAPI/BridgeAPINetworkerProvider.swift
Sources/Core/Extensions/Bundle+Extensions.swift
Sources/Core/FBApplicationDelegate.swift
Sources/Core/Needs Conversion/AppEventsLogger.swift
Sources/Core/Needs Conversion/Settings.swift
Sources/Core/Needs Conversion/TimeSpentDataStore.swift
Sources/Placeholder.swift
Tests/Core/ButtonTests.swift
Tests/Core/FBApplicationDelegateTests.swift
Tests/Core/Helpers/FakeAppEventsLogger.swift
Tests/Core/Helpers/FakeNotificationCenter.swift
Tests/Core/Helpers/FakeSettings.swift
Tests/Core/Helpers/FakeTimeSpentDataStore.swift
Tests/Core/Helpers/UserDefaultsSpy.swift
Tests/Core/ProfilePictureViewTests.swift
Tests/Core/UserProfileServiceTests.swift

Additions to `FBApplicationDelegate` for tracking events and responding to app lifecycle events
Unit tests.

Libary load signals

---

Sources/Core/GraphRequestConnection.swift
Sources/Core/Needs Conversion/Settings.swift
Tests/Core/GraphRequestConnectionConfigurationTests.swift
Tests/Core/GraphRequestConnectionTests.swift
Tests/Core/Helpers/FakeSettings.swift
Tests/Core/SettingsTests.swift

Adds headers to graph requests. Adds user agent property to settings
Unit tests should all pass.

Adding Headers and UserAgent to GraphRequests

---

Sources/Login/LoginManager.swift

Exposes the login manager to fix issue #458

Exposes LoginManager via typealias

---

Cartfile.resolved

Updates dependencies to version 5.4.0.

Update dependencies to version 5.4.0

---

.github/CODEOWNERS

Adds additional code owner
N/A

Adding additional codeowner

---

README.md
ROADMAP.md

Proposal for outlining strategy for modernization in the README
N/A

Future plans announcement

---

.github/CODEOWNERS

Adds additional codeowners
N/A

Adding additional codeowners

---

FacebookSwift.xcodeproj/project.pbxproj

Swiftlint should only run on Debug builds as it has no bearing on Release builds.
See: #432 
N/A

Updates Swiftlint phase to only run on debug builds

---

README.md

Codifies test terminology to avoid future confusion.
N/A

Updates readme to include test terminology

---

Announcement.md
MigrationGuide.md

Outlines plan to deprecate API along with migration guide
N/A

Announcement regarding future of SDK
