README.md

Clarify Carthage and sub-project Getting Started instructions in README.

---

README.md

To successfully build the SDK by your own you need to run `git submodule update --init --recursive` first.

Add missing `git submodule` command to README

---

README.md

Use possessive when referencing frameworks' dependencies.

Fix possessive typos in README

---

FacebookSwift.xcodeproj/project.pbxproj
Samples/Catalog/Sources/GraphAPIReadViewController.swift
Sources/Core/GraphRequest/GraphAPIVersion.swift
Sources/Core/GraphRequest/GraphRequest.swift
Sources/Core/GraphRequest/GraphRequestProtocol.Bridge.swift
Sources/Core/GraphRequest/GraphRequestProtocol.swift

The new type is both string and float literal convertible.
Also fix the dichotomy in ObjC SDK that requires `v` prefix for the apiVersion (the swift one shouldn't).
Fixes #28

Change type GraphRequestProtocol.apiVersion from String to concrete GraphAPIVersion.

---

FacebookSwift.xcodeproj/project.pbxproj
Sources/Core/UserProfile/UserProfile.FetchResult.swift
Sources/Core/UserProfile/UserProfile.swift

New APIs to fetch and refresh `UserProfile`.
Tested via a small test app - works as intended, as well as updates the current user's profile.

Add ability to fetch and refresh UserProfile.

---

FacebookSwift.xcodeproj/project.pbxproj
Samples/Catalog/Sources/AppDelegate.swift
Sources/Core/Common/SDKApplicationDelegate.swift

Preventing name clashes, as `ApplicationDelegate` is likely to exist in the app module.
Closes #35

Rename ApplicationDelegate to SDKApplicationDelegate to avoid name clashes.

---

Sources/Share/Content/OpenGraph/OpenGraphShareContent.swift

This slipped beneath the radar for the initial release.
Fixes #39.

Add constructor for OpenGraphShareContent.

---

Samples/Catalog/Sources/LoginManagerViewController.swift
Sources/Login/LoginManager.swift

Improve ambiguous `logIn()` function names in LoginManager.

---

Sources/Login/LoginManager.swift

didSet doesn't work when property initialization, so sdkManager's properties are should be set explicitly when initialization.
P.S. 
I read CONTRIBUTING.md there describing `Add tests`. But I couldn't find test codes in this project.
Please tell me where test codes are if I should add tests. 😉

Fix LoginManager's initializer problem.

---

Sources/Core/AppEvents/AppEventsLogger.swift
Sources/Core/GraphRequest/GraphRequestConnection.swift

This adds a new static variable for the current user Id as well as the ability to update the custom user properties.
Superseds and closes #103

Add userId and user properties to AppEventsLogger.

---

Configurations/FacebookCore.modulemap
FacebookSwift.xcodeproj/project.pbxproj
Sources/Core/Internal/FBSDKSettingsInitializer.h
Sources/Core/Internal/FBSDKSettingsInitializer.m
Sources/Core/Internal/FacebookSwift-Bridging-Header.h

This will allow to distinguish between Swift SDK and Objective SDK API calls.

Set `swift` user agent suffix in FBSDKSettings

---

Sources/Core/Common/SDKSettings.swift

In Xcode 10 Line 151 has this compiler error: Argument type 'SDKLoggingBehavior?' does not conform to expected type 'Sequence'
Update flatMap which was was deprecated in Swift 4.1 and use CompactMap
closes #235

XCode 10 - Update flatMap to compactMap as deprecated

---

Sources/Core/GraphRequest/GraphRequestConnection.swift

due to 'internal' protection level
For Xcode 10

Fix GraphRequestConnection some function are inaccessible for Xcode 10

---

Sources/Share/Dialogs/ShareDialog/ShareDialog.swift

weak definition is making problem when you want to use callbacks
The weak definition is making a problem (delegate always nil) when you want to use callback.

Fix for callback problem

---

Sources/Core/AppEvents/AppEventParameterName.swift

updated the facebook-ios-sdk submodule to the latest version
added content to AppEventParameterName which was already mentioned in facebook swift sdk documentation
This adds a new enum value content to AppEventParameterName to expose FBSDKAppEventParameterNameContent.
Fixes #241

Add content to AppEventParameterName

---

Sources/Core/AppEvents/AppEvent.Builtin.swift
Sources/Core/AppEvents/AppEventParameterName.swift

Fixing the following AppEvent creator functions to match the [
https://developers.facebook.com/docs/app-events/getting-started-app-events-ios#event-names](documentation)
- ViewedContent
- Searched
- Rated
- AddedToCart
- AddedToWishList
- InitiatedCheckout
- SpentCredits

Fixing the AppEvent creator functions to match the documentation

---

.travis.yml
FacebookSwift.xcodeproj/project.pbxproj
Sources/Core/Common/SDKApplicationDelegate.swift

Swift 4.2 moves to split out some of the ApplicationDelegate keys to be named better, this implements that. It solves build errors when using the Xcode 10 GM build.
Fixes #262

Update to Swift 4.2

---

Sources/Share/Content/Photo/Photo.swift

Fix #264 FBSDKSharePhoto property setter error

---

Sources/Login/LoginResult.swift

When a user declines a publish permission with the "NOT NOW" button, `init` of the `LoginResult` fails with fatal error because of `sdkResult.token` is `nil`

handle sdkResult.token == nil

---

.swiftlint.yml

Hey there 👋,
This PR should solve #300. With the new release of Swifttlint 0.29.1 a new rule was introduced:
>The lint command now exits with a code of 2 when not using pinned version defined as swiftlint_version in the configuration file.
This new rule would cause a failure when a different version is used. In this PR I removed the pinned version as IMO it would break the build for users not using the pinned version. Another alternative would be to force the users to pin that version 🤔, but IMHO I think removing it is better. 
At the end this PR can be resumed in :
* Remove the swiftlint_version in the .swiflint.yml file.
I thought about upgrading the dependencies in the `Cartfile` but that would break the build with a new issue related to `FBSDKShareKit` so I decided to keep this simple …

Remove the swiftlint_version in the .swiflint.yml file

---

README.md

Readme fails to mention that FBSDKLoginKit.framework is required to use FacebookLogin.framework, and FBSDKShareKit.framework is required to use FacebookShare.framework.

Add missing frameworks to readme

---

Sources/Core/GraphRequest/GraphRequestConnection.swift

Update use of deprecated FBSDKGraphConnection method to the renamed method. Possible cause of issue #324

Update use of deprecated ObjC SDK method

---

FacebookSwift.xcodeproj/project.pbxproj
Sources/Core/AccessToken.swift
Sources/Core/FacebookCoreTests/AccessTokenTests.swift
Sources/Core/FacebookCoreTests/Fixtures/AccessTokenFixtures.swift
Sources/Core/FacebookCoreTests/PermissionTests.swift
Sources/Core/Permission.swift

Introduces a permissions enum with known cases.
Introduces a Permission enum to use as the canonical type for representing permissions and declined permissions.
Test Plan: Unit tests should all pass. Code coverage should remain at 100%

Introducing Permission enum

---

.swiftlint.yml
Tests/Core/.swiftlint.yml

HomeBrew does not allow us to specify a Swiftlint version to install. Instead it defaults to the latest version. This approach is not compatible with keeping a required version in the .swiftlint.yml since this is likely to break with new releases of Swiftlint. In short, we should not specify a required version having control over which version is installed.

Removing swiftlint version check

---

Cartfile.resolved

Resolve https://github.com/facebook/facebook-swift-sdk/issues/468.
Update facebook-objc-sdk to fix build failure on Xcode 11.
1. Download and setup Xcode 11
2. Build SwiftCatalog in this repository
- Build fails without this changes
- Error: `Implicit conversion loses integer precision: 'FBSDKAppInviteDestination' (aka 'enum FBSDKAppInviteDestination') to 'int'`
- Build succeeds with this changes
- This also works well with carthage build.

Update to support ObjC v5.2.3

---

FacebookSwift.xcodeproj/project.pbxproj
Samples/Catalog/Sources/AppDelegate.swift
Samples/Catalog/Sources/AppInviteViewController.swift
Samples/Catalog/Sources/CustomAppEventViewController.swift
Samples/Catalog/Sources/GraphAPIPostViewController.swift
Samples/Catalog/Sources/GraphAPIReadViewController.swift
Samples/Catalog/Sources/LoginManagerViewController.swift
Samples/Catalog/Sources/ManualAppEventViewController.swift
Samples/Catalog/Sources/ShareAPIViewController.swift
Samples/Catalog/Sources/ShareDialogViewController.swift
Samples/Catalog/SwiftCatalog.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Sources/Core/FBSDKCoreKit+Typealiases.swift
Sources/Login/FBSDKLoginKit+Typealiases.swift
Sources/Share/FBSDKShareKit+Typealiases.swift

The sample catalog was forced to pull in multiple libraries to perform basic tasks. This is a code smell that can be handled by exposing the necessary types to relevant libraries in the form of typealiases.
The downside of this approach is that it is a heavily manual process. There is a finite number of types however so this isn't the end of the world. A future PR will have a more comprehensive list accounting of the types available in the 'FBSDK' name-spaced dependencies. 
The real question is whether or not some of these types are so generically named that they should have an 'FB' prefix.
Open project and build 'SwiftCatalog'

Updating sample project to not import dependent libraries

---

FacebookSwift.xcodeproj/project.pbxproj
FacebookSwift.xcodeproj/xcshareddata/xcschemes/FacebookLogin.xcscheme
Samples/Catalog/Sources/LoginManagerViewController.swift
Sources/Login/AuthenticationService.swift
Sources/Login/FBSDKLoginKit+Typealiases.swift
Sources/Login/LoginInformation.swift
Sources/Login/LoginManager.swift
Tests/.swiftlint.yml
Tests/FacebookLoginTests/Fakes/FakeAuthenticationService.swift
Tests/FacebookLoginTests/LoginInformationTests.swift
Tests/FacebookLoginTests/LoginManagerTests.swift
Tests/FacebookLoginTests/Samples/SampleAccessToken.swift
Tests/FacebookLoginTests/Samples/SampleError.swift
Tests/FacebookLoginTests/Samples/SampleLoginManagerLoginResult.swift
Tests/FacebookLoginTests/Spies/AuthenticationServiceSpy.swift

Updates to LoginManager
**Breaking changes:**
* LoginManager is now a struct. It is a separate abstraction layer from the underlying FBSDKLoginManager implementation.
* `logIn` method signature is updated to use actual Result type
* `logIn` method signature is updated to require a completion. Fire and forget makes little sense in the context of authentication.
**Additionally:**
* Adds sanity check around returned permissions
* Adds tests around service
* Adds layer of separation between LoginManager and FBSDKLoginManager
Unit tests were added and should all pass.

Updates LoginManager
